### ISSUE TITLE
about run python app/main.py

### ISSUE THREAD

**Issue by bz2233** [enriquetomasmb/fedstellar#26]
(fedstellar-venv) (ljw) b2@ps:~/zrd/fedstellar-venv/fedstellar$ python app/main.py

                            ______       _     _       _ _            
                            |  ___|     | |   | |     | | |           
                            | |_ ___  __| |___| |_ ___| | | __ _ _ __ 
                            |  _/ _ \/ _` / __| __/ _ \ | |/ _` | '__|
                            | ||  __/ (_| \__ \ ||  __/ | | (_| | |   
                            \_| \___|\__,_|___/\__\___|_|_|\__,_|_|   
                         A Platform for Decentralized Federated Learning 
                       Enrique Tomás Martínez Beltrán (enriquetomas@um.es)
                    
[INFO] - 2024-01-02 21:56:24,721 - Controller - Saving configuration in environment variables...
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Common Commands:
  run         Create and run a new container from an image
  exec        Execute a command in a running container
  ps          List containers
  build       Build an image from a Dockerfile
  pull        Download an image from a registry
  push        Upload an image to a registry
  images      List images
  login       Log in to a registry
  logout      Log out from a registry
  search      Search Docker Hub for images
  version     Show the Docker version information
  info        Display system-wide information

Management Commands:
  builder     Manage builds
  checkpoint  Manage checkpoints
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  plugin      Manage plugins
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Swarm Commands:
  config      Manage Swarm configs
  node        Manage Swarm nodes
  secret      Manage Swarm secrets
  service     Manage Swarm services
  stack       Manage Swarm stacks
  swarm       Manage Swarm

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  wait        Block until one or more containers stop, then print their exit codes

Global Options:
      --config string      Location of client config files (default "/home/b2/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket to connect to
  -l, --log-level string   Set the logging level ("debug", "info", "warn", "error", "fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/b2/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/b2/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/b2/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Run 'docker COMMAND --help' for more information on a command.

For more help on how to use Docker, head to https://docs.docker.com/go/guides/

[ERROR] - 2024-01-02 21:56:24,758 - Controller - Docker Compose failed to start, please check if Docker is running and Docker Compose is installed.
[ERROR] - 2024-01-02 21:56:24,758 - Controller - Command '['docker', 'compose', '-f', '/home/b2/zrd/fedstellar-venv/fedstellar/fedstellar/frontend/docker-compose.yml', 'up', '--build', '-d']' returned non-zero exit status 125.
Traceback (most recent call last):
  File "app/main.py", line 134, in <module>
    Controller(args).start()
  File "/home/b2/zrd/fedstellar-venv/fedstellar/app/../fedstellar/controller.py", line 134, in start
    self.run_frontend()
  File "/home/b2/zrd/fedstellar-venv/fedstellar/app/../fedstellar/controller.py", line 474, in run_frontend
    raise e
  File "/home/b2/zrd/fedstellar-venv/fedstellar/app/../fedstellar/controller.py", line 458, in run_frontend
    subprocess.check_call(
  File "/home/b2/anaconda3/envs/ljw/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'compose', '-f', '/home/b2/zrd/fedstellar-venv/fedstellar/fedstellar/frontend/docker-compose.yml', 'up', '--build', '-d']' returned non-zero exit status 125.

how to fix this error?

**Comment by enriquetomasmb** [comment]
Hi @bz2233, you must install Docker Compose and have Docker Engine running before deploying Fedstellar. You can take a look [here](https://docs.docker.com/compose/install/) to install the compatible version of Docker Compose.

**Comment by bz2233** [comment]
> Hi @bz2233, you must install Docker Compose and have Docker Engine running before deploying Fedstellar. You can take a look [here](https://docs.docker.com/compose/install/) to install the compatible version of Docker Compose.

Thank you very much for your help, now i can run python app/main.py below are the print when run python app/main.py and it can run very well, but i can't reach http://127.0.0.1:5000/ 
and i change controller.py add sudo in the front because i can't run the docker without sudo.
could you please check this and tell me what to do

![image](https://github.com/enriquetomasmb/fedstellar/assets/67300948/59ee0254-698e-46fb-abfd-0975543f2939)


(fedstellar-venv) (ljw) b2@ps:~/zrd/fedstellar-venv/fedstellar$ python app/main.py

                            ______       _     _       _ _            
                            |  ___|     | |   | |     | | |           
                            | |_ ___  __| |___| |_ ___| | | __ _ _ __ 
                            |  _/ _ \/ _` / __| __/ _ \ | |/ _` | '__|
                            | ||  __/ (_| \__ \ ||  __/ | | (_| | |   
                            \_| \___|\__,_|___/\__\___|_|_|\__,_|_|   
                         A Platform for Decentralized Federated Learning 
                       Enrique Tomás Martínez Beltrán (enriquetomas@um.es)
                    
[INFO] - 2024-01-03 11:30:09,666 - Controller - Saving configuration in environment variables...
[+] Building 0.0s (26/26) FINISHED                                                                                                                                                      docker:default
 => [fedstellar-frontend internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                   0.0s
 => [fedstellar-frontend internal] load build definition from Dockerfile                                                                                                                          0.0s
 => => transferring dockerfile: 1.75kB                                                                                                                                                            0.0s
 => [fedstellar-frontend internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                               0.0s
 => [fedstellar-frontend internal] load build context                                                                                                                                             0.0s
 => => transferring context: 84B                                                                                                                                                                  0.0s
 => [fedstellar-frontend  1/21] FROM docker.io/library/ubuntu:22.04                                                                                                                               0.0s
 => CACHED [fedstellar-frontend  2/21] RUN apt-get update && apt-get install -y software-properties-common                                                                                        0.0s
 => CACHED [fedstellar-frontend  3/21] RUN add-apt-repository ppa:deadsnakes/ppa                                                                                                                  0.0s
 => CACHED [fedstellar-frontend  4/21] RUN apt-get update && apt-get install -y python3.8 python3.8-dev python3.8-distutils python3.8-venv                                                        0.0s
 => CACHED [fedstellar-frontend  5/21] RUN apt-get install -y nginx                                                                                                                               0.0s
 => CACHED [fedstellar-frontend  6/21] RUN apt-get install -y curl net-tools                                                                                                                      0.0s
 => CACHED [fedstellar-frontend  7/21] RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py                                                                                                0.0s
 => CACHED [fedstellar-frontend  8/21] RUN python3.8 get-pip.py                                                                                                                                   0.0s
 => CACHED [fedstellar-frontend  9/21] RUN apt-get update && apt-get install -y gcc git dos2unix                                                                                                  0.0s
 => CACHED [fedstellar-frontend 10/21] RUN apt-get install -y ca-certificates curl gnupg                                                                                                          0.0s
 => CACHED [fedstellar-frontend 11/21] RUN install -m 0755 -d /etc/apt/keyrings                                                                                                                   0.0s
 => CACHED [fedstellar-frontend 12/21] RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg                                                0.0s
 => CACHED [fedstellar-frontend 13/21] RUN chmod a+r /etc/apt/keyrings/docker.gpg                                                                                                                 0.0s
 => CACHED [fedstellar-frontend 14/21] RUN echo   "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   "$(. /etc/os-rele  0.0s
 => CACHED [fedstellar-frontend 15/21] RUN apt-get update                                                                                                                                         0.0s
 => CACHED [fedstellar-frontend 16/21] RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin                                                    0.0s
 => CACHED [fedstellar-frontend 17/21] COPY requirements-frontend.txt .                                                                                                                           0.0s
 => CACHED [fedstellar-frontend 18/21] RUN python3.8 -m pip install --ignore-installed -r requirements-frontend.txt                                                                               0.0s
 => CACHED [fedstellar-frontend 19/21] COPY start_services.sh .                                                                                                                                   0.0s
 => CACHED [fedstellar-frontend 20/21] RUN dos2unix start_services.sh                                                                                                                             0.0s
 => CACHED [fedstellar-frontend 21/21] RUN chmod +x start_services.sh                                                                                                                             0.0s
 => [fedstellar-frontend] exporting to image                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                                           0.0s
 => => writing image sha256:4898d1df0d47ff60b624bbfcb6fe9c3b322602d2e44acffacb0bf1b897f42eee                                                                                                      0.0s
 => => naming to docker.io/library/fedstellar-frontend                                                                                                                                            0.0s
[+] Running 1/0
 ✔ Container fedstellar-frontend  Running                                                                                                                                                         0.0s 
[INFO] - 2024-01-03 11:30:09,980 - Controller - Fedstellar Frontend is running at port 6060
[INFO] - 2024-01-03 11:30:09,980 - Controller - Press Ctrl+C for exit from Fedstellar (global exit)
^C[INFO] - 2024-01-03 12:19:11,598 - Controller - Closing Fedstellar (exiting from components)... Please wait
^C[INFO] - 2024-01-03 12:19:11,838 - Controller - Closing Fedstellar (exiting from components)... Please wait
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22ancestor%22%3A%7B%22fedstellar%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22fedstellar%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22ancestor%22%3A%7B%22fedstellar-gpu%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22fedstellar-gpu%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22ancestor%22%3A%7B%22fedstellar-frontend%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22fedstellar-frontend%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22ancestor%22%3A%7B%22fedstellar-statistics%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22fedstellar-statistics%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/networks": dial unix /var/run/docker.sock: connect: permission denied

**Comment by bz2233** [comment]
![image](https://github.com/enriquetomasmb/fedstellar/assets/67300948/7e780a0a-e873-4dc2-bca2-93edc6d8faf7)
and when i Installing the NVIDIA Container Toolkit, should i do this Configuration

**Comment by enriquetomasmb** [comment]
Hi, again @bz2233. Regarding the docker issue, you probably need to check the permissions to access "docker.sock". The controller has to manage the sock to deploy the federation. Look at the possible issues and the solutions [here](https://fedstellar.enriquetomasmb.com/installation.html#possible-issues-during-the-installation-or-execution). 

Concerning your second question, yes! You must follow that tutorial to install the runtime docker to allow participant access to the GPU.

**Comment by bz2233** [comment]
Thanks for your help again and now i have done with these issues and when i run&nbsp;python app/main.py it seems perfectly.
but i still can not open&nbsp;http://127.0.0.1:5000/. Then i check the logs&nbsp;in app/logs/server.log. there is noting in it.
then i&nbsp;take a look at the docker logs of the fedstellar-frontend container:

docker logs fedstellar-frontend it shows that "Error response from daemon: No such container: fedstellar-frontend" and&nbsp;

i don't know why this happens even after search the error in the internet. Could you please check why this happens?

Is this because the computer networks problem that i can't open&nbsp;http://127.0.0.1:5000/.Thank you very much again!


loneliness
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "enriquetomasmb/fedstellar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [enriquetomasmb/fedstellar] about run python app/main.py (Issue #26)





 
Hi, again @bz2233. Regarding the docker issue, you probably need to check the permissions to access "docker.sock". The controller has to manage the sock to deploy the federation. Look at the possible issues and the solutions here.
 
Concerning your second question, yes! You must follow that tutorial to install the runtime docker to allow participant access to the GPU.

**Comment by enriquetomasmb** [comment]
> docker logs fedstellar-frontend it shows that "Error response from daemon: No such container: fedstellar-frontend"

It is necessary to have fedstellar-frontend deployed to use "docker logs fedstellar-frontend". Try it before pressing CTRL+C (based on your image)
